version: '2'
services:
  mariadb:
    image: mariadb:10.1
    container_name: ${MYSQL_CONTAINER}
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - back
  wordpress:
    image: zeroindex/wordpress
    container_name: ${WORDPRESS_CONTAINER}
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - "${PORT}:80"
    volumes:
      - ./src/theme:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./src/uploads:/var/www/html/wp-content/uploads
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WP_DEBUG=true
    networks:
      - front
      - back
networks:
  front:
  back:
